### ISSUE TITLE
ISGW sync only working one-direction

### ISSUE THREAD

**Issue by NullOranje** [Nexenta/edgefs#379]
### Steps to reproduce the behavior
1. On a two fresh clusters (Primary and Secondary), create a new cluster/tenant/bucket `test1/t1/bk1`
2. Setup NFS to volume to map `bk1` to Kubernetes application using CSI driver
3. Create and serve ISGW on both primary and secondary clusters
```
efscli service create isgw gw-test1
efscli service serve gw-test1 test1/t1/bk1
```

isgw.yaml
```yaml
apiVersion: edgefs.rook.io/v1
kind: ISGW
metadata:
  name: gw-test1
  namespace: rook-edgefs
spec:
  direction: "send+receive"                  # I/O flow direction: send, receive or send-receive
  remoteURL: "ccow://10.102.101.241:31313"   # Primary Site
  # remoteURL: "ccow://10.102.108.21:31313"     # Secondary Site
  serviceType: "NodePort"
  externalPort: 31313
```
4. From inside a container on the primary site, create a new file `touch file1`
5. Wait for replication to occur
6. See the new file inside a container on the secondary site
7. From inside a container on the secondary site, create a new file `touch file2`
8. Wait for replication to occur
9. **File does not appear**

### Expected behavior
Files created on the secondary site will be replicated on the primary site

### Actual behavior
Object replication happening in one direction

### EdgeFS version
v1.2.72

### Deployment type

- [x] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

v1.14.3 created via Kubespray

- [x] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other
