### ISSUE TITLE
Error: Rtlfs devices should be more then 3 on all nodes

### ISSUE THREAD

**Issue by tobiasholst** [Nexenta/edgefs#385]
### Summary 
I'm trying to install a setup without raw disk but get the following error in the operator logs: 
```
edgefs-op-cluster: failed to create cluster in namespace rook-edgefs. Failed to create [rook-edgefs] EdgeFS cluster configuration. Error: Rtlfs devices should be more then 3 on all nodes summary
```
From the end of one of the discover pods:
```rook-discover: available devices: [{Name:sda Parent: HasChildren:false DevLinks:/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0 Size:81923145728 UUID:sgdiskNotFound Serial:0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0 Type:disk Rotational:true Readonly:false Partitions:[{Name:sda1 Size:81922080256 Label: Filesystem:ext4}] Filesystem: Vendor:QEMU Model:QEMU_HARDDISK WWN: WWNVendorExtension: Empty:false}]``` 
### Steps to reproduce the behavior
```
cd cluster/examples/kubernetes/edgefs
nano cluster.yaml
```
comment out the useAllDevices option and change the cluster version to 1.2.72
```
kubectl create -f operator.yaml
```
wait until all in Running state
```
kubectl create -f cluster.yaml
```
### Expected behavior
```kubectl -n rook-edgefs get pod``` shows cluster pods
### Actual behavior
```
kubectl -n rook-edgefs get pod
```
> No resources found in rook-edgefs namespace.

### EdgeFS version
Operator: master
Cluster: 1.2.72
### Deployment type
- [x] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

Rancher v2.3.0 on 4 cloud servers, 1 master, 3 workers

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [x] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
how is your kind: Cluster section looks like?

**Comment by tobiasholst** [comment]
```
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:1.2.72
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  storage: 
    useAllNodes: true
```
